### PR TITLE
panel practice generator

### PR DESCRIPTION
**Pull request by Mattlavelle966**
complete and working panel practice generator, needs API key in .env to function.

### CODE REVIEW

**Comment by Mattlavelle966** [comment]
complete and working panel practice generator, needs API key in .env to function.

**Comment by astrosaturn** [comment]
Code looks good, but I think it needs some more functionality (which can come later) and a few other things.

- Look into gathering a user response after and having chatGPT create a response to the user
- Add some more documentation (block comment under function explaining it)
- Fix typos/grammar in code comments and prompt
- Feed ChatGPT the username for some more personality? 

We can go over some of these implementations in a call if you'd like

**Comment by Mattlavelle966** [comment]
I'll work on the user input soon.

**Comment by Mattlavelle966** [comment]
Also if you'd like please notes with your name in the file and I'll read
them.

**Pull request merged**
